export const companyData = {
  name: "Space Exploration Technologies Corp.",
  founder: "Elon Musk",
  founded: 2002,
  employees: 13000,
  ceo: "Elon Musk",
  cto: "Elon Musk",
  coo: "Gwynne Shotwell",
  summary:
    "SpaceX designs, manufactures and launches advanced rockets and spacecraft. The company was founded in 2002 to revolutionize space technology, with the ultimate goal of enabling people to live on other planets.",
  launch_sites: 3,
  valuation: 210_000_000_000,
};

export const rocketsData = [
  {
    id: "falcon1",
    name: "Falcon 1",
    description:
      "The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX. On September 28, 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.",
    active: false,
    first_flight: "2006-03-24",
    country: "Republic of the Marshall Islands",
    stages: 2,
    boosters: 0,
    cost_per_launch: 6_700_000,
    success_rate_pct: 40,
    mass: { kg: 30146 },
    height: { meters: 22.25 },
    diameter: { meters: 1.68 },
    engines: {
      number: 1,
      type: "merlin",
      version: "1C",
      propellant_1: "liquid oxygen",
      propellant_2: "RP-1 kerosene",
      thrust_to_weight: 96,
    },
    payload_weights: [{ id: "leo", name: "Low Earth Orbit", kg: 450 }],
    flickr_images: [
      "https://images2.imgbox.com/94/f2/NN6Ph45r_o.png",
      "https://images2.imgbox.com/72/96/QMXwDyjN_o.png",
    ],
    wikipedia: "https://en.wikipedia.org/wiki/Falcon_1",
  },
  {
    id: "falcon9",
    name: "Falcon 9",
    description:
      "Falcon 9 is a two-stage rocket designed and manufactured by SpaceX for the reliable and safe transport of satellites and the Dragon spacecraft into orbit. Falcon 9 is the world's first orbital class reusable rocket.",
    active: true,
    first_flight: "2010-06-04",
    country: "United States",
    stages: 2,
    boosters: 0,
    cost_per_launch: 62_000_000,
    success_rate_pct: 98,
    mass: { kg: 549054 },
    height: { meters: 70 },
    diameter: { meters: 3.7 },
    engines: {
      number: 9,
      type: "merlin",
      version: "1D+",
      propellant_1: "liquid oxygen",
      propellant_2: "RP-1 kerosene",
      thrust_to_weight: 180.1,
    },
    payload_weights: [
      { id: "leo", name: "Low Earth Orbit", kg: 22800 },
      { id: "gto", name: "Geosynchronous Transfer Orbit", kg: 8300 },
      { id: "mars", name: "Mars Orbit", kg: 4020 },
    ],
    flickr_images: [
      "https://images2.imgbox.com/3c/6b/bExNgMKO_o.png",
      "https://images2.imgbox.com/7e/b0/0ZLIf0b2_o.png",
    ],
    wikipedia: "https://en.wikipedia.org/wiki/Falcon_9",
  },
  {
    id: "falconheavy",
    name: "Falcon Heavy",
    description:
      "With the ability to lift into orbit over 54 metric tons (119,000 lb)--a mass equivalent to a 737 jetliner loaded with passengers, crew, luggage and fuel--Falcon Heavy can lift more than twice the payload of the next closest operational vehicle, the Delta IV Heavy.",
    active: true,
    first_flight: "2018-02-06",
    country: "United States",
    stages: 2,
    boosters: 2,
    cost_per_launch: 90_000_000,
    success_rate_pct: 100,
    mass: { kg: 1420788 },
    height: { meters: 70 },
    diameter: { meters: 12.2 },
    engines: {
      number: 27,
      type: "merlin",
      version: "1D+",
      propellant_1: "liquid oxygen",
      propellant_2: "RP-1 kerosene",
      thrust_to_weight: 224.7,
    },
    payload_weights: [
      { id: "leo", name: "Low Earth Orbit", kg: 63800 },
      { id: "gto", name: "Geosynchronous Transfer Orbit", kg: 26700 },
      { id: "mars", name: "Mars Orbit", kg: 16800 },
      { id: "pluto", name: "Pluto Trajectory", kg: 3500 },
    ],
    flickr_images: [
      "https://images2.imgbox.com/a7/ca/TepSZ40s_o.png",
      "https://images2.imgbox.com/5e/ff/R7YjZPvI_o.png",
    ],
    wikipedia: "https://en.wikipedia.org/wiki/Falcon_Heavy",
  },
  {
    id: "starship",
    name: "Starship",
    description:
      "Starship is a fully reusable transportation system designed to carry both crew and cargo to Earth orbit, the Moon, Mars and beyond. Starship is the world's largest and most powerful launch vehicle, with over twice the thrust of any previous rocket.",
    active: true,
    first_flight: "2023-04-20",
    country: "United States",
    stages: 2,
    boosters: 0,
    cost_per_launch: 10_000_000,
    success_rate_pct: 50,
    mass: { kg: 5000000 },
    height: { meters: 120 },
    diameter: { meters: 9 },
    engines: {
      number: 33,
      type: "raptor",
      version: "2",
      propellant_1: "liquid oxygen",
      propellant_2: "liquid methane",
      thrust_to_weight: 150,
    },
    payload_weights: [
      { id: "leo", name: "Low Earth Orbit", kg: 150000 },
      { id: "mars", name: "Mars Orbit", kg: 100000 },
    ],
    flickr_images: [
      "https://images2.imgbox.com/6f/d8/kGrFXgYS_o.png",
    ],
    wikipedia: "https://en.wikipedia.org/wiki/SpaceX_Starship",
  },
];

export const launchesData = [
  {
    id: "5eb87cd9ffd86e000604b32a",
    mission_name: "FalconSat",
    launch_date_utc: "2006-03-24T22:30:00.000Z",
    launch_success: false,
    details: "Engine failure at 33 seconds and loss of vehicle",
    rocket: { rocket_name: "Falcon 1", rocket_type: "Merlin A", second_stage: { payloads: [{ payload_id: "FalconSAT-2", payload_type: "Satellite", payload_mass_kg: 20, orbit: "LEO", nationality: "USA", manufacturer: "USAF Academy", customers: ["DARPA"] }] } },
    launch_site: { site_name_long: "Kwajalein Atoll Omelek Island" },
    links: { mission_patch: "https://images2.imgbox.com/40/e3/GypSkayF_o.png", mission_patch_small: "https://images2.imgbox.com/3c/0e/T8irings5_o.png", video_link: "https://www.youtube.com/watch?v=0a_00nJ_Y88", wikipedia: "https://en.wikipedia.org/wiki/DemoSat", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [],
  },
  {
    id: "5eb87cdcffd86e000604b32d",
    mission_name: "RatSat",
    launch_date_utc: "2008-09-28T23:15:00.000Z",
    launch_success: true,
    details: "Ratsat was carried to orbit on the first successful orbital launch of any privately funded and developed, liquid-propellant rocket (the SpaceX Falcon 1)",
    rocket: { rocket_name: "Falcon 1", rocket_type: "Merlin C", second_stage: { payloads: [{ payload_id: "ratsat", payload_type: "Satellite", payload_mass_kg: 165, orbit: "LEO", nationality: "USA", manufacturer: "SpaceX", customers: ["SpaceX"] }] } },
    launch_site: { site_name_long: "Kwajalein Atoll Omelek Island" },
    links: { mission_patch: "https://images2.imgbox.com/40/e3/GypSkayF_o.png", mission_patch_small: "https://images2.imgbox.com/e9/c9/T8inings.png", video_link: "https://www.youtube.com/watch?v=9x0PFvBV8KM", wikipedia: "https://en.wikipedia.org/wiki/Ratsat", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [],
  },
  {
    id: "5eb87ce1ffd86e000604b333",
    mission_name: "Falcon 9 Test Flight",
    launch_date_utc: "2010-06-04T18:45:00.000Z",
    launch_success: true,
    details: "The first flight of Falcon 9 with a dummy Dragon capsule payload. Launched from SLC-40 at Cape Canaveral.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "v1.0", second_stage: { payloads: [{ payload_id: "Dragon Qualification Unit", payload_type: "Dragon Boilerplate", payload_mass_kg: null, orbit: "LEO", nationality: "USA", manufacturer: "SpaceX", customers: ["SpaceX"] }] } },
    launch_site: { site_name_long: "Cape Canaveral Air Force Station Space Launch Complex 40" },
    links: { mission_patch: "https://images2.imgbox.com/b7/21/V8HRh4cG_o.png", mission_patch_small: "https://images2.imgbox.com/b7/21/V8HRh4cG_o.png", video_link: "https://www.youtube.com/watch?v=nxSIAkB-Hxc", wikipedia: "https://en.wikipedia.org/wiki/Falcon_9_Flight_1", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [],
  },
  {
    id: "5eb87ce3ffd86e000604b335",
    mission_name: "COTS Demo Flight 1",
    launch_date_utc: "2010-12-08T15:43:00.000Z",
    launch_success: true,
    details: "First Dragon spacecraft test flight. Dragon orbited Earth twice and then splashed down in the Pacific Ocean.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "v1.0", second_stage: { payloads: [{ payload_id: "Dragon", payload_type: "Dragon 1.0", payload_mass_kg: null, orbit: "LEO", nationality: "USA", manufacturer: "SpaceX", customers: ["SpaceX"] }] } },
    launch_site: { site_name_long: "Cape Canaveral Air Force Station Space Launch Complex 40" },
    links: { mission_patch: "https://images2.imgbox.com/f5/8e/lHxX5lyC_o.png", mission_patch_small: "https://images2.imgbox.com/f5/8e/lHxX5lyC_o.png", video_link: "https://www.youtube.com/watch?v=yEqNqCyD6UM", wikipedia: "https://en.wikipedia.org/wiki/SpaceX_COTS_Demo_Flight_1", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [],
  },
  {
    id: "5eb87ce4ffd86e000604b336",
    mission_name: "CRS-1",
    launch_date_utc: "2012-10-08T00:35:00.000Z",
    launch_success: true,
    details: "First successful commercial resupply mission to the International Space Station. Dragon carried 400 kg of supplies.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "v1.0", second_stage: { payloads: [{ payload_id: "Dragon", payload_type: "Dragon 1.0", payload_mass_kg: 400, orbit: "ISS", nationality: "USA", manufacturer: "SpaceX", customers: ["NASA"] }] } },
    launch_site: { site_name_long: "Cape Canaveral Air Force Station Space Launch Complex 40" },
    links: { mission_patch: "https://images2.imgbox.com/e2/cd/LznwxFpY_o.png", mission_patch_small: "https://images2.imgbox.com/e2/cd/LznwxFpY_o.png", video_link: "https://www.youtube.com/watch?v=pMsvr55cTZ0", wikipedia: "https://en.wikipedia.org/wiki/SpaceX_CRS-1", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [],
  },
  {
    id: "5eb87cebffd86e000604b340",
    mission_name: "ORBCOMM OG2 Mission 1",
    launch_date_utc: "2014-07-14T19:15:00.000Z",
    launch_success: true,
    details: "First use of the reusable first stage. The stage performed a controlled descent and water landing in the Atlantic Ocean.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "v1.1", second_stage: { payloads: [{ payload_id: "ORBCOMM-OG2-M1", payload_type: "Satellite", payload_mass_kg: 1316, orbit: "LEO", nationality: "USA", manufacturer: "Sierra Nevada Corporation", customers: ["ORBCOMM"] }] } },
    launch_site: { site_name_long: "Cape Canaveral Air Force Station Space Launch Complex 40" },
    links: { mission_patch: "https://images2.imgbox.com/f3/77/KheW1wPK_o.png", mission_patch_small: "https://images2.imgbox.com/f3/77/KheW1wPK_o.png", video_link: "https://www.youtube.com/watch?v=2iXWyvlec9g", wikipedia: "https://en.wikipedia.org/wiki/ORBCOMM_OG2", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [],
  },
  {
    id: "5eb87cf9ffd86e000604b34f",
    mission_name: "OG2 Mission 2",
    launch_date_utc: "2015-12-22T01:29:00.000Z",
    launch_success: true,
    details: "First successful landing of a Falcon 9 first stage at Landing Zone 1, Cape Canaveral. This was a major milestone for reusable rockets.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "v1.1", second_stage: { payloads: [{ payload_id: "ORBCOMM-OG2-M2", payload_type: "Satellite", payload_mass_kg: 2034, orbit: "LEO", nationality: "USA", manufacturer: "Sierra Nevada Corporation", customers: ["ORBCOMM"] }] } },
    launch_site: { site_name_long: "Cape Canaveral Air Force Station Space Launch Complex 40" },
    links: { mission_patch: "https://images2.imgbox.com/02/45/LViVjFEo_o.png", mission_patch_small: "https://images2.imgbox.com/02/45/LViVjFEo_o.png", video_link: "https://www.youtube.com/watch?v=O5bTbVbe4e4", wikipedia: "https://en.wikipedia.org/wiki/ORBCOMM_OG2", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [],
  },
  {
    id: "5eb87d03ffd86e000604b35a",
    mission_name: "Iridium NEXT Mission 1",
    launch_date_utc: "2017-01-14T17:54:00.000Z",
    launch_success: true,
    details: "SpaceX launched 10 Iridium NEXT communication satellites. The booster landed successfully on the drone ship JRTI in the Pacific Ocean.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "FT", second_stage: { payloads: [{ payload_id: "Iridium NEXT 1", payload_type: "Satellite", payload_mass_kg: 9600, orbit: "Polar LEO", nationality: "USA", manufacturer: "Thales Alenia Space", customers: ["Iridium Communications"] }] } },
    launch_site: { site_name_long: "Vandenberg Air Force Base Space Launch Complex 4E" },
    links: { mission_patch: "https://images2.imgbox.com/e1/c9/NjU42m1T_o.png", mission_patch_small: "https://images2.imgbox.com/e1/c9/NjU42m1T_o.png", video_link: "https://www.youtube.com/watch?v=t5MqPLFpRFk", wikipedia: "https://en.wikipedia.org/wiki/Iridium_satellite_constellation", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [{ name: "Just Read The Instructions", type: "Drone Ship", home_port: "Los Angeles" }],
  },
  {
    id: "5eb87d0effd86e000604b361",
    mission_name: "SES-10",
    launch_date_utc: "2017-03-30T22:27:00.000Z",
    launch_success: true,
    details: "First reflight of an orbital class rocket. The booster used here was recovered from the CRS-8 mission in April 2016 and refurbished for this mission.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "FT", second_stage: { payloads: [{ payload_id: "SES-10", payload_type: "Satellite", payload_mass_kg: 5300, orbit: "GTO", nationality: "Luxembourg", manufacturer: "Airbus Defence and Space", customers: ["SES"] }] } },
    launch_site: { site_name_long: "Kennedy Space Center Historic Launch Complex 39A" },
    links: { mission_patch: "https://images2.imgbox.com/a3/c0/TBuwESmQ_o.png", mission_patch_small: "https://images2.imgbox.com/a3/c0/TBuwESmQ_o.png", video_link: "https://www.youtube.com/watch?v=xNqs_S-zEBY", wikipedia: "https://en.wikipedia.org/wiki/SES-10", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [{ name: "Of Course I Still Love You", type: "Drone Ship", home_port: "Port Canaveral" }],
  },
  {
    id: "5eb87d2bffd86e000604b376",
    mission_name: "Falcon Heavy Test Flight",
    launch_date_utc: "2018-02-06T20:45:00.000Z",
    launch_success: true,
    details: "Maiden flight of the Falcon Heavy rocket carrying Elon Musk's personal Tesla Roadster. Both side boosters landed simultaneously at Cape Canaveral.",
    rocket: { rocket_name: "Falcon Heavy", rocket_type: "FT", second_stage: { payloads: [{ payload_id: "Tesla Roadster", payload_type: "Satellite", payload_mass_kg: 1350, orbit: "Heliocentric", nationality: "USA", manufacturer: "Tesla", customers: ["Elon Musk"] }] } },
    launch_site: { site_name_long: "Kennedy Space Center Historic Launch Complex 39A" },
    links: { mission_patch: "https://images2.imgbox.com/a6/fb/HLMCXPLb_o.png", mission_patch_small: "https://images2.imgbox.com/a6/fb/HLMCXPLb_o.png", video_link: "https://www.youtube.com/watch?v=wbSwFU6tY1c", wikipedia: "https://en.wikipedia.org/wiki/Elon_Musk%27s_Tesla_Roadster", reddit_campaign: null, presskit: null, flickr_images: ["https://images2.imgbox.com/a7/ca/TepSZ40s_o.png", "https://images2.imgbox.com/5e/ff/R7YjZPvI_o.png"] },
    ships: [],
  },
  {
    id: "5eb87d2dffd86e000604b378",
    mission_name: "Iridium NEXT Mission 5",
    launch_date_utc: "2018-03-30T14:13:00.000Z",
    launch_success: true,
    details: "SpaceX launched 10 more Iridium NEXT satellites. This was a reused booster from the Iridium NEXT Mission 1.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "B4", second_stage: { payloads: [{ payload_id: "Iridium NEXT 5", payload_type: "Satellite", payload_mass_kg: 9600, orbit: "Polar LEO", nationality: "USA", manufacturer: "Thales Alenia Space", customers: ["Iridium Communications"] }] } },
    launch_site: { site_name_long: "Vandenberg Air Force Base Space Launch Complex 4E" },
    links: { mission_patch: "https://images2.imgbox.com/05/20/mJdEoYCY_o.png", mission_patch_small: "https://images2.imgbox.com/05/20/mJdEoYCY_o.png", video_link: "https://www.youtube.com/watch?v=Cz_tg_f3FFQ", wikipedia: "https://en.wikipedia.org/wiki/Iridium_satellite_constellation", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [{ name: "Just Read The Instructions", type: "Drone Ship", home_port: "Los Angeles" }],
  },
  {
    id: "5eb87d36ffd86e000604b381",
    mission_name: "Telstar 19V",
    launch_date_utc: "2018-07-22T05:50:00.000Z",
    launch_success: true,
    details: "Telstar 19V is a communications satellite operated by Telesat. It is one of the heaviest commercial communications satellites ever launched.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "B5", second_stage: { payloads: [{ payload_id: "Telstar 19V", payload_type: "Satellite", payload_mass_kg: 7076, orbit: "GTO", nationality: "Canada", manufacturer: "SSL", customers: ["Telesat"] }] } },
    launch_site: { site_name_long: "Cape Canaveral Air Force Station Space Launch Complex 40" },
    links: { mission_patch: "https://images2.imgbox.com/c3/fa/Wwa1pOYN_o.png", mission_patch_small: "https://images2.imgbox.com/c3/fa/Wwa1pOYN_o.png", video_link: "https://www.youtube.com/watch?v=xybp6zLaGx4", wikipedia: "https://en.wikipedia.org/wiki/Telstar_19V", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [{ name: "Of Course I Still Love You", type: "Drone Ship", home_port: "Port Canaveral" }],
  },
  {
    id: "5eb87d44ffd86e000604b38e",
    mission_name: "CRS-16",
    launch_date_utc: "2018-12-05T18:16:00.000Z",
    launch_success: true,
    details: "Dragon carried 2,617 kg of supplies to the International Space Station. The booster experienced a grid fin hydraulic pump failure and performed a water landing.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "B5", second_stage: { payloads: [{ payload_id: "Dragon", payload_type: "Dragon 1.0", payload_mass_kg: 2617, orbit: "ISS", nationality: "USA", manufacturer: "SpaceX", customers: ["NASA"] }] } },
    launch_site: { site_name_long: "Cape Canaveral Air Force Station Space Launch Complex 40" },
    links: { mission_patch: "https://images2.imgbox.com/d3/13/dFKpCNnD_o.png", mission_patch_small: "https://images2.imgbox.com/d3/13/dFKpCNnD_o.png", video_link: "https://www.youtube.com/watch?v=C6-IfEOQQSM", wikipedia: null, reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [],
  },
  {
    id: "5eb87d4effd86e000604b396",
    mission_name: "Starlink Mission",
    launch_date_utc: "2019-05-24T02:30:00.000Z",
    launch_success: true,
    details: "SpaceX launched 60 Starlink satellites into orbit, the first batch of its planned mega-constellation to provide global broadband internet coverage.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "B5", second_stage: { payloads: [{ payload_id: "Starlink V0.9", payload_type: "Satellite", payload_mass_kg: 13620, orbit: "LEO", nationality: "USA", manufacturer: "SpaceX", customers: ["SpaceX"] }] } },
    launch_site: { site_name_long: "Cape Canaveral Air Force Station Space Launch Complex 40" },
    links: { mission_patch: "https://images2.imgbox.com/9d/64/RktfiV7V_o.png", mission_patch_small: "https://images2.imgbox.com/9d/64/RktfiV7V_o.png", video_link: "https://www.youtube.com/watch?v=HStrFHZK9Ys", wikipedia: "https://en.wikipedia.org/wiki/Starlink", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [{ name: "Of Course I Still Love You", type: "Drone Ship", home_port: "Port Canaveral" }],
  },
  {
    id: "5eb87d4fffd86e000604b397",
    mission_name: "CRS-17",
    launch_date_utc: "2019-05-04T06:48:00.000Z",
    launch_success: true,
    details: "Dragon carried 2,490 kg of supplies and science experiments to the International Space Station. First flight of a Dragon capsule that had flown previously.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "B5", second_stage: { payloads: [{ payload_id: "Dragon", payload_type: "Dragon 1.0", payload_mass_kg: 2490, orbit: "ISS", nationality: "USA", manufacturer: "SpaceX", customers: ["NASA"] }] } },
    launch_site: { site_name_long: "Cape Canaveral Air Force Station Space Launch Complex 40" },
    links: { mission_patch: "https://images2.imgbox.com/d3/13/dFKpCNnD_o.png", mission_patch_small: "https://images2.imgbox.com/d3/13/dFKpCNnD_o.png", video_link: "https://www.youtube.com/watch?v=bIJ_GKl3my8", wikipedia: null, reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [{ name: "Of Course I Still Love You", type: "Drone Ship", home_port: "Port Canaveral" }],
  },
  {
    id: "5eb87d13ffd86e000604b368",
    mission_name: "Crew Dragon Demo-1",
    launch_date_utc: "2019-03-02T07:49:00.000Z",
    launch_success: true,
    details: "First uncrewed flight test of the Dragon 2 spacecraft. Dragon docked with the ISS and returned to Earth after 5 days.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "B5", second_stage: { payloads: [{ payload_id: "Crew Dragon DM-1", payload_type: "Crew Dragon", payload_mass_kg: 12519, orbit: "ISS", nationality: "USA", manufacturer: "SpaceX", customers: ["NASA"] }] } },
    launch_site: { site_name_long: "Kennedy Space Center Historic Launch Complex 39A" },
    links: { mission_patch: "https://images2.imgbox.com/ab/8a/Wyc9K7fv_o.png", mission_patch_small: "https://images2.imgbox.com/ab/8a/Wyc9K7fv_o.png", video_link: "https://www.youtube.com/watch?v=giNhaEzv_PI", wikipedia: "https://en.wikipedia.org/wiki/Crew_Dragon_Demo-1", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [{ name: "Of Course I Still Love You", type: "Drone Ship", home_port: "Port Canaveral" }, { name: "GO Searcher", type: "Recovery Ship", home_port: "Port Canaveral" }],
  },
  {
    id: "5eb87d62ffd86e000604b3a6",
    mission_name: "Crew Dragon Demo-2",
    launch_date_utc: "2020-05-30T19:22:00.000Z",
    launch_success: true,
    details: "First crewed orbital flight of Dragon 2, carrying NASA astronauts Bob Behnken and Doug Hurley to the ISS. First crewed American orbital launch since STS-135 in 2011.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "B5", second_stage: { payloads: [{ payload_id: "Crew Dragon DM-2", payload_type: "Crew Dragon", payload_mass_kg: 12519, orbit: "ISS", nationality: "USA", manufacturer: "SpaceX", customers: ["NASA"] }] } },
    launch_site: { site_name_long: "Kennedy Space Center Historic Launch Complex 39A" },
    links: { mission_patch: "https://images2.imgbox.com/6c/cb/oFGjKUCj_o.png", mission_patch_small: "https://images2.imgbox.com/6c/cb/oFGjKUCj_o.png", video_link: "https://www.youtube.com/watch?v=xY96v0OIcK4", wikipedia: "https://en.wikipedia.org/wiki/Crew_Dragon_Demo-2", reddit_campaign: null, presskit: null, flickr_images: ["https://images2.imgbox.com/b0/db/34d6UMHQ_o.jpg", "https://images2.imgbox.com/cb/2e/JcDJFhEh_o.jpg"] },
    ships: [{ name: "GO Navigator", type: "Recovery Ship", home_port: "Port Canaveral" }],
  },
  {
    id: "5eb87d85ffd86e000604b3c8",
    mission_name: "Starlink 12 (v1.0)",
    launch_date_utc: "2020-10-18T12:25:00.000Z",
    launch_success: true,
    details: "SpaceX launched 60 Starlink v1.0 satellites. This was the 100th successful Falcon 9 mission.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "B5", second_stage: { payloads: [{ payload_id: "Starlink v1.0 L12", payload_type: "Satellite", payload_mass_kg: 15600, orbit: "LEO", nationality: "USA", manufacturer: "SpaceX", customers: ["SpaceX"] }] } },
    launch_site: { site_name_long: "Kennedy Space Center Historic Launch Complex 39A" },
    links: { mission_patch: "https://images2.imgbox.com/9d/64/RktfiV7V_o.png", mission_patch_small: "https://images2.imgbox.com/9d/64/RktfiV7V_o.png", video_link: "https://www.youtube.com/watch?v=J2bCj7M5_3E", wikipedia: "https://en.wikipedia.org/wiki/Starlink", reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [{ name: "Just Read The Instructions", type: "Drone Ship", home_port: "Los Angeles" }],
  },
  {
    id: "5ef6d05b9c3a4d0a6081b5a7",
    mission_name: "Crew-1",
    launch_date_utc: "2020-11-16T00:27:00.000Z",
    launch_success: true,
    details: "First operational crewed flight of Dragon 2. Carried NASA astronauts Mike Hopkins, Victor Glover, Shannon Walker, and JAXA astronaut Soichi Noguchi to the ISS.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "B5", second_stage: { payloads: [{ payload_id: "Crew Dragon Resilience", payload_type: "Crew Dragon", payload_mass_kg: 12519, orbit: "ISS", nationality: "USA", manufacturer: "SpaceX", customers: ["NASA"] }] } },
    launch_site: { site_name_long: "Kennedy Space Center Historic Launch Complex 39A" },
    links: { mission_patch: "https://images2.imgbox.com/18/91/HaJYLxIc_o.png", mission_patch_small: "https://images2.imgbox.com/18/91/HaJYLxIc_o.png", video_link: "https://www.youtube.com/watch?v=O1URpDlbGBs", wikipedia: "https://en.wikipedia.org/wiki/Crew_Dragon_Resilience", reddit_campaign: null, presskit: null, flickr_images: ["https://images2.imgbox.com/a0/f8/499OverE_o.jpg"] },
    ships: [{ name: "GO Navigator", type: "Recovery Ship", home_port: "Port Canaveral" }],
  },
  {
    id: "5fe3a15eb3467846b3242161",
    mission_name: "Transporter-1",
    launch_date_utc: "2021-01-24T15:00:00.000Z",
    launch_success: true,
    details: "SpaceX's first dedicated rideshare mission, carrying 143 small satellites — a record for the most satellites launched on a single rocket.",
    rocket: { rocket_name: "Falcon 9", rocket_type: "B5", second_stage: { payloads: [{ payload_id: "Transporter-1", payload_type: "Rideshare", payload_mass_kg: null, orbit: "SSO", nationality: "Various", manufacturer: "Various", customers: ["Various"] }] } },
    launch_site: { site_name_long: "Cape Canaveral Space Force Station Space Launch Complex 40" },
    links: { mission_patch: "https://images2.imgbox.com/4b/bd/d8UxLh4q_o.png", mission_patch_small: "https://images2.imgbox.com/4b/bd/d8UxLh4q_o.png", video_link: "https://www.youtube.com/watch?v=9I0UYXSa0EI", wikipedia: null, reddit_campaign: null, presskit: null, flickr_images: [] },
    ships: [{ name: "Just Read The Instructions", type: "Drone Ship", home_port: "Los Angeles" }],
  },
];

export const upcomingLaunchesData = [
  {
    id: "upcoming-1",
    mission_name: "Starlink Group 10-5",
    launch_date_utc: "2026-06-15T14:00:00.000Z",
    details: "SpaceX will launch another batch of Starlink satellites to continue expanding its broadband constellation.",
    rocket: { rocket_name: "Falcon 9" },
    launch_site: { site_name_long: "Cape Canaveral Space Force Station Space Launch Complex 40" },
  },
  {
    id: "upcoming-2",
    mission_name: "CRS-32",
    launch_date_utc: "2026-07-01T10:30:00.000Z",
    details: "Dragon will deliver cargo and science experiments to the International Space Station as part of NASA's Commercial Resupply Services contract.",
    rocket: { rocket_name: "Falcon 9" },
    launch_site: { site_name_long: "Kennedy Space Center Historic Launch Complex 39A" },
  },
  {
    id: "upcoming-3",
    mission_name: "Starship IFT-9",
    launch_date_utc: "2026-08-01T15:00:00.000Z",
    details: "Ninth integrated flight test of the Starship launch system, continuing development of full and rapid reusability of both Super Heavy and Starship.",
    rocket: { rocket_name: "Starship" },
    launch_site: { site_name_long: "SpaceX Starbase, Boca Chica, Texas" },
  },
  {
    id: "upcoming-4",
    mission_name: "Crew-11",
    launch_date_utc: "2026-07-12T09:00:00.000Z",
    details: "Operational crewed flight to the International Space Station carrying four astronauts for a long-duration science expedition.",
    rocket: { rocket_name: "Falcon 9" },
    launch_site: { site_name_long: "Kennedy Space Center Historic Launch Complex 39A" },
  },
  {
    id: "upcoming-5",
    mission_name: "O3b mPOWER-7,8",
    launch_date_utc: "2026-09-15T20:00:00.000Z",
    details: "Launch of two more satellites for SES's O3b mPOWER medium Earth orbit communications constellation.",
    rocket: { rocket_name: "Falcon 9" },
    launch_site: { site_name_long: "Cape Canaveral Space Force Station Space Launch Complex 40" },
  },
];


export const launchPadsData = [
  {
    id: "vafb-slc-4e",
    name: "VAFB SLC 4E",
    full_name: "Vandenberg Space Force Base Space Launch Complex 4E",
    locality: "Vandenberg Space Force Base",
    region: "California",
    details:
      "SLC-4E at Vandenberg Space Force Base is SpaceX's West Coast launch site, primarily used for polar and sun-synchronous orbit missions. The pad was originally built for the Titan III rocket and later converted for Falcon 9 use.",
    status: "active",
    launch_attempts: 62,
    launch_successes: 61,
    wikipedia: "https://en.wikipedia.org/wiki/Vandenberg_Space_Launch_Complex_4",
    images: [
      "https://images2.imgbox.com/e7/d7/v0w3BJdp_o.png",
    ],
  },
  {
    id: "ccafs-slc-40",
    name: "CCAFS SLC 40",
    full_name: "Cape Canaveral Space Force Station Space Launch Complex 40",
    locality: "Cape Canaveral",
    region: "Florida",
    details:
      "SLC-40 is SpaceX's primary East Coast launch pad, handling the bulk of Falcon 9 commercial satellite missions and ISS cargo runs. After a 2016 pad explosion during a static fire, it was rebuilt and returned to service in late 2017.",
    status: "active",
    launch_attempts: 95,
    launch_successes: 94,
    wikipedia: "https://en.wikipedia.org/wiki/Cape_Canaveral_Space_Launch_Complex_40",
    images: [
      "https://images2.imgbox.com/e0/a7/FNjvKlXo_o.png",
    ],
  },
  {
    id: "ksc-lc-39a",
    name: "KSC LC 39A",
    full_name: "Kennedy Space Center Historic Launch Complex 39A",
    locality: "Kennedy Space Center",
    region: "Florida",
    details:
      "LC-39A is SpaceX's most storied launch pad, originally built for the Apollo Saturn V and later used for the Space Shuttle. SpaceX leased it in 2014 and uses it for crewed Dragon missions, Falcon Heavy launches, and high-energy commercial payloads.",
    status: "active",
    launch_attempts: 71,
    launch_successes: 71,
    wikipedia: "https://en.wikipedia.org/wiki/Kennedy_Space_Center_Launch_Complex_39",
    images: [
      "https://images2.imgbox.com/80/b0/GNqHKuqE_o.png",
    ],
  },
  {
    id: "starbase-texas",
    name: "Starbase",
    full_name: "SpaceX Starbase, Boca Chica",
    locality: "Boca Chica Village",
    region: "Texas",
    details:
      "Starbase is SpaceX's dedicated Starship development and launch facility located on the southern tip of Texas near the Mexican border. The site hosts the Orbital Launch Mount (OLM) used for all Starship integrated flight tests, and includes the Mechazilla catch tower capable of catching returning boosters mid-air.",
    status: "active",
    launch_attempts: 8,
    launch_successes: 4,
    wikipedia: "https://en.wikipedia.org/wiki/SpaceX_Starbase",
    images: [
      "https://images2.imgbox.com/6f/d8/kGrFXgYS_o.png",
    ],
  },
  {
    id: "kwajalein-atoll",
    name: "Omelek Island",
    full_name: "Kwajalein Atoll Omelek Island",
    locality: "Omelek Island",
    region: "Marshall Islands",
    details:
      "Omelek Island in the Kwajalein Atoll was SpaceX's very first launch site, used exclusively for the Falcon 1 rocket between 2006 and 2009. Its remote Pacific location provided safe ocean corridors for the first four Falcon 1 flights. The site is now decommissioned.",
    status: "retired",
    launch_attempts: 5,
    launch_successes: 2,
    wikipedia: "https://en.wikipedia.org/wiki/Omelek_Island",
    images: [
      "https://images2.imgbox.com/c5/83/GJYIgKc0_o.png",
    ],
  },
];
